image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: Install node dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Install package dependencies
          caches:
            - docker
          script:
            - apt-get update
            - apt-get install -y wine mono rpm dpkg fakeroot
    - step:
        name: publish 
        caches:
          - node
        script:
          - npm run publish:all