image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: Install node dependencies
          caches:
            - node
          script:
            - npm install

      - step:
          name: Install package dependencies
          caches:
            - node
            - apt-cache # Custom cache for apt
          script:
            - apt-get update
            - apt-get install -y gnupg2 software-properties-common
            - dpkg --add-architecture i386
            - apt-get update
            - apt-get install -y wine32 wine wine64 libwine mono-devel rpm dpkg fakeroot
          artifacts:
            - /var/cache/apt/**
            - /usr/bin/mono*
            - /usr/lib/*mono*/**
            - /usr/lib/*wine*/**
            - /usr/bin/wine*

    - parallel:
      - step:
          name: publish-win
          caches:
            - node
            - apt-cache # Use cached apt packages
          script:
            - npm run publish:win
          artifacts:
            - out/**

      - step:
          name: publish-linux
          caches:
            - node
            - apt-cache
          script:
            - npm run publish:linux
          artifacts:
            - out/**

definitions:
  caches:
    apt-cache: /var/cache/apt  # Cache for apt packages
