image: node:18

pipelines:
  default:
    - step:
        name: Install node dependencies
        caches:
          - node
        script:
          - npm install

    - parallel:
      - step:
          name: publish-win
          run-on:
            - windows
          caches:
            - node
          script:
            - npm run publish:win

      - step:
          name: publish-linux
          caches:
            - node
          script:
            - apt-get install -y rpm
            - rpmbuild --version
            - npm run publish:linux
