image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: Install node dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Install package dependencies
          caches:
            - node
          script:
            - apt-get update && apt-get install -y gnupg2 software-properties-common
            - dpkg --add-architecture i386
            - apt-get update
            - apt-get install -y wine32 wine wine64 libwine mono-devel rpm dpkg fakeroot
    - step:
        name: publish 
        caches:
          - node
        script:
          - npm run publish:all
        artifacts:
          - out/**