image: node:18

pipelines:
  default:
    - parallel:
        - step:
            name: Install dependencies
            caches:
              - node
            script:
              - npm install
        - step:
            name: publish 
            caches:
              - node
            script:
              - npm run publish:all