image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: Install node dependencies
          caches:
            - node
          script:
            - npm install
      - step:
          name: Install package dependencies
          caches:
            - node
          script:
            - apt-get update && apt-get install -y gnupg2 software-properties-common
            - dpkg --add-architecture i386
            - apt-get update
            - apt-get install -y wine32 wine wine64 libwine mono-devel rpm dpkg fakeroot
    - parallel:
      - step:
          name: publish-win
          script:
            - npm run publish:win
          artifacts:
            - out/**
      - step:
          name: publish-linux
          script:
            - npm run publish:linux
          artifacts:
            - out/**
      # - step:
      #     name: publish-mac
      #     runs-on:
      #       - macos
      #     script:
      #       - npm run publish:mac
      #     artifacts:
      #       - out/**